# Generated by Django 6.0 on 2025-12-31 16:54

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='chairs',
            field=models.ManyToManyField(blank=True, related_name='conferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='conference',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='unique_conference_title_ci'),
        ),
    ]
