# Generated by Django 5.2.5 on 2026-10-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='allowed_extensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='conference',
            name='sources_multiple',
            field=models.BooleanField(default=False),
        ),
    ]
