# Generated by Django 5.2.5 on 2026-10-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='review_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='review_start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='submission_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='submission_start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
