# Generated by Django 5.2.5 on 2026-10-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_conference_allowed_extensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='allowed_extensions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
