# Generated by Django 6.0 on 2025-12-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_file', models.FileField(upload_to='articles/')),
                ('status', models.CharField(choices=[('reception', 'Recepción'), ('bidding', 'Bidding'), ('assignment', 'Asignación'), ('review', 'Revisión'), ('selection', 'Selección'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='reception', max_length=20)),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('poster', 'Poster')], max_length=10)),
                ('abstract', models.TextField(max_length=300)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='articles/sources/')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
