# Generated by Django 5.2.5 on 2026-10-03 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlehistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='articlehistory',
            name='target_user',
        ),
        migrations.AddField(
            model_name='articlehistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_history_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlehistory',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_history_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
