# Generated by Django 5.2.5 on 2026-10-03 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlehistory'),
    ]

    # 0003 already creates created_by and reviewed_by. Keep this migration so
    # databases that previously recorded 0004 retain a continuous history.
    operations = []
