# Generated by Django 5.2.5 on 2026-10-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='source_file',
        ),
    ]
