# Generated by Django 5.2.5 on 2026-10-02 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
        ('reviewer', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('reviewer', 'article'), name='unique_bid_per_reviewer_article'),
        ),
    ]
