# Generated by Django 5.2.5 on 2026-10-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
        ('reviewer', '0003_reviewerinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.notification')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reviewer.reviewerinvitation')),
            ],
            bases=('notification.notification',),
        ),
    ]
