# Generated by Django 5.2.5 on 2026-10-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_bid_unique_bid_per_reviewer_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='chair_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reviewversion',
            name='chair_comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
