# Generated by Django 6.0 on 2025-12-31 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('capacity', models.IntegerField()),
                ('threshold_percentage', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('improvement_threshold', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)])),
                ('locked_selection', models.BooleanField(blank=True, default=False, help_text='If true, the selection type cannot be modified.')),
                ('type_selection', models.CharField(blank=True, choices=[('ScoreThresholdSelection', 'ScoreThresholdSelection'), ('CutoffSelection', 'CutoffSelection')], help_text='Type of selection used for this session.', max_length=50, null=True)),
            ],
        ),
    ]
