# Generated by Django 6.0 on 2025-12-31 16:54

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0002_initial'),
        ('conference_session', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='chairs',
            field=models.ManyToManyField(blank=True, related_name='session', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='conference.conference'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('conference'), name='unique_session_title_per_conference_ci'),
        ),
    ]
